{% set name = "ctapipe-io-nectarcam" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_nectarcam-{{ version }}.tar.gz
  sha256: 3578fe5cc354e8a729430964ba7fd6c936eaf112733082e3d8f3d499a1589bd3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python =3
    - setuptools >=64.0.3
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python =3
    - astropy
    - ctapipe =0.12
    - numpy <1.23
    - protozfits =2.0
    - pytables >=3.7

test:
  imports:
    - ctapipe_io_nectarcam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/ctapipe_io_nectarcam
  summary: ctapipe plugin for reading NectarCam files
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jlenain
