{% set name = "ctapipe-io-nectarcam" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_nectarcam-{{ version }}.tar.gz
  sha256: d358c1d2951128d75369db488efb2b0860b51426862b73b6878a875ad28a68b7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python =3
    - setuptools >=64.0.3
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python =3
    - astropy
    - ctapipe =0.19
    - protozfits

test:
  imports:
    - ctapipe_io_nectarcam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/ctapipe_io_nectarcam
  summary: ctapipe plugin for reading NectarCam files
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jlenain
