{% set name = "ctapipe-io-nectarcam" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_nectarcam-{{ version }}.tar.gz
  sha256: 6241c1ffe74149fea5f7916b4dc70a5401d2f8f1c07c06f8c8f847dc85be2981

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.3
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - ctapipe =0.24
    - protozfits
    - scipy

test:
  imports:
    - ctapipe_io_nectarcam
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cta-observatory/ctapipe_io_nectarcam
  summary: ctapipe plugin for reading NectarCam files
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jlenain
