{% set name = "ctapipe-io-nectarcam" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctapipe_io_nectarcam-{{ version }}.tar.gz
  sha256: c664d1039078e855ff365b2ed131fac5af0579e71f4048119a85296462fc1a1c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.3
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - astropy
    - ctapipe =0.24
    - protozfits
    - scipy

test:
  imports:
    - ctapipe_io_nectarcam
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cta-observatory/ctapipe_io_nectarcam
  summary: ctapipe plugin for reading NectarCam files
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jlenain
